import { WatchlistSummary, WatchlistSymbolLive, WatchlistDiffItem } from './types';

export const INITIAL_WATCHLISTS: WatchlistSummary[] = [
  {
    id: 'core-tech',
    name: 'Core Tech & Semis',
    symbolCount: 8,
    flaggedCount: 3,
    lastUpdated: '12m ago',
  },
  {
    id: 'biopharma-edge',
    name: 'BioPharma & Genomics',
    symbolCount: 5,
    flaggedCount: 2,
    lastUpdated: '34m ago',
  },
  {
    id: 'macro-etfs',
    name: 'Macro & Rates',
    symbolCount: 4,
    flaggedCount: 1,
    lastUpdated: '1h ago',
  },
  {
    id: 'empty-watchlist',
    name: 'Speculative Sandbox',
    symbolCount: 0,
    flaggedCount: 0,
    lastUpdated: '2d ago',
  },
];

export const INITIAL_SYMBOLS_BY_WATCHLIST: Record<string, WatchlistSymbolLive[]> = {
  'core-tech': [
    {
      symbol: 'NVDA',
      companyName: 'NVIDIA Corporation',
      price: 132.84,
      changePct: 4.82,
      volumeRatio: 2.8,
      attentionScore: 94,
      why: 'Data center Blackwell supply chain ramp confirmed ahead of schedule; institutional block flows up 310%',
      tags: ['Volume', 'Breakout', 'Catalyst'],
      dataStatus: 'live',
      sparkline: [126.5, 127.1, 128.4, 129.8, 129.2, 131.0, 132.84],
      marketCap: '$3.28T',
      high52w: 140.76,
      low52w: 45.11,
    },
    {
      symbol: 'ASML',
      companyName: 'ASML Holding N.V.',
      price: 884.2,
      changePct: -3.41,
      volumeRatio: 2.1,
      attentionScore: 88,
      why: 'Export curb revisions to China expanded by Dutch regulator; Q4 bookings risk flagged by Morgan Stanley',
      tags: ['Regulatory', 'Volume', 'Guidance'],
      dataStatus: 'live',
      sparkline: [915.0, 910.2, 902.5, 898.0, 891.4, 887.0, 884.2],
      marketCap: '$352B',
      high52w: 1110.0,
      low52w: 590.2,
    },
    {
      symbol: 'PLTR',
      companyName: 'Palantir Technologies Inc.',
      price: 36.42,
      changePct: 7.15,
      volumeRatio: 3.4,
      attentionScore: 91,
      why: 'S&P 500 rebalancing inclusion announced after close; AIP bootcamps conversion accelerating',
      tags: ['Earnings', 'Volume', 'Breakout'],
      dataStatus: 'live',
      sparkline: [33.8, 34.1, 34.9, 35.5, 35.2, 36.0, 36.42],
      marketCap: '$81.4B',
      high52w: 37.5,
      low52w: 14.48,
    },
    {
      symbol: 'TSM',
      companyName: 'Taiwan Semiconductor Mfg.',
      price: 174.5,
      changePct: 1.84,
      volumeRatio: 1.4,
      attentionScore: 68,
      why: '3nm capacity fully booked through 2026; price hike of 5-8% absorbed by top 5 hyperscalers',
      tags: ['Pricing Power', 'Guidance'],
      dataStatus: 'live',
      sparkline: [171.2, 171.8, 172.5, 173.1, 173.8, 174.0, 174.5],
      marketCap: '$905B',
      high52w: 193.47,
      low52w: 84.52,
    },
    {
      symbol: 'AAPL',
      companyName: 'Apple Inc.',
      price: 228.15,
      changePct: -0.42,
      volumeRatio: 0.85,
      attentionScore: 32,
      why: 'Normal consolidation ahead of iPhone 16 cycle kickoff; replacement supercycle expectations tempered',
      tags: ['Consolidation'],
      dataStatus: 'live',
      sparkline: [229.1, 228.8, 228.5, 228.0, 228.4, 228.3, 228.15],
      marketCap: '$3.49T',
      high52w: 237.23,
      low52w: 164.08,
    },
    {
      symbol: 'MSFT',
      companyName: 'Microsoft Corporation',
      price: 421.3,
      changePct: 0.65,
      volumeRatio: 0.92,
      attentionScore: 38,
      why: 'Copilot enterprise churn in line with consensus estimates; CapEx expenditure run-rate stable',
      tags: ['Enterprise'],
      dataStatus: 'delayed',
      sparkline: [419.0, 419.8, 420.5, 421.0, 420.8, 421.1, 421.3],
      marketCap: '$3.13T',
      high52w: 468.35,
      low52w: 309.45,
    },
    {
      symbol: 'AMD',
      companyName: 'Advanced Micro Devices, Inc.',
      price: 154.2,
      changePct: -1.92,
      volumeRatio: 1.6,
      attentionScore: 64,
      why: 'MI300 ramp healthy but server CPU market share gains slowing against Intel Sierra Forest',
      tags: ['Competitive', 'Volume'],
      dataStatus: 'live',
      sparkline: [157.2, 156.4, 155.8, 155.0, 154.6, 154.8, 154.2],
      marketCap: '$249B',
      high52w: 227.3,
      low52w: 94.04,
    },
    {
      symbol: 'ARM',
      companyName: 'Arm Holdings plc',
      price: 139.6,
      changePct: 3.25,
      volumeRatio: 1.75,
      attentionScore: 72,
      why: 'Armv9 licensing royalties expanded to next-gen flagship mobile & server chips with +2x fee rate',
      tags: ['Intellectual Property', 'Guidance'],
      dataStatus: 'delayed',
      sparkline: [135.0, 136.2, 137.4, 138.0, 137.5, 138.9, 139.6],
      marketCap: '$144B',
      high52w: 188.75,
      low52w: 46.5,
    },
  ],
  'biopharma-edge': [
    {
      symbol: 'VRTX',
      companyName: 'Vertex Pharmaceuticals Inc.',
      price: 488.75,
      changePct: 5.42,
      volumeRatio: 2.9,
      attentionScore: 92,
      why: 'FDA grants priority review for non-opioid acute pain candidate Suzetrigine with PDUFA date set',
      tags: ['FDA Approval', 'Volume', 'Breakout'],
      dataStatus: 'live',
      sparkline: [463.0, 468.5, 474.0, 480.2, 482.5, 485.0, 488.75],
      marketCap: '$126B',
      high52w: 510.6,
      low52w: 343.1,
    },
    {
      symbol: 'LLY',
      companyName: 'Eli Lilly and Company',
      price: 942.1,
      changePct: 2.35,
      volumeRatio: 1.8,
      attentionScore: 84,
      why: 'Zepbound single-dose vials launched at 50% discount to broaden direct-to-consumer cash pay access',
      tags: ['Pricing Strategy', 'Catalyst'],
      dataStatus: 'live',
      sparkline: [920.0, 924.5, 931.0, 936.2, 938.0, 940.5, 942.1],
      marketCap: '$895B',
      high52w: 972.53,
      low52w: 540.2,
    },
    {
      symbol: 'CRSP',
      companyName: 'CRISPR Therapeutics AG',
      price: 52.3,
      changePct: -4.12,
      volumeRatio: 2.3,
      attentionScore: 81,
      why: 'Casgevy commercial rollout centers slower than expected due to complex pre-conditioning regimen',
      tags: ['Earnings', 'Volume'],
      dataStatus: 'delayed',
      sparkline: [54.8, 54.2, 53.6, 53.1, 52.8, 52.5, 52.3],
      marketCap: '$4.4B',
      high52w: 90.3,
      low52w: 37.6,
    },
    {
      symbol: 'ISRG',
      companyName: 'Intuitive Surgical, Inc.',
      price: 492.4,
      changePct: 0.85,
      volumeRatio: 1.1,
      attentionScore: 45,
      why: 'da Vinci 5 placement trajectory steady across academic medical centers; procedure growth at 16%',
      tags: ['Procedure Volume'],
      dataStatus: 'live',
      sparkline: [488.0, 489.2, 490.5, 491.0, 491.8, 492.0, 492.4],
      marketCap: '$175B',
      high52w: 504.0,
      low52w: 254.8,
    },
    {
      symbol: 'BMY',
      companyName: 'Bristol Myers Squibb Co.',
      price: 49.15,
      changePct: -0.35,
      volumeRatio: 0.78,
      attentionScore: 28,
      why: 'Cobston patent cliff overhang largely priced in; dividend yield defensive support holding',
      tags: ['Defensive'],
      dataStatus: 'delayed',
      sparkline: [49.3, 49.2, 49.25, 49.1, 49.18, 49.12, 49.15],
      marketCap: '$99B',
      high52w: 61.2,
      low52w: 39.3,
    },
  ],
  'macro-etfs': [
    {
      symbol: 'TLT',
      companyName: 'iShares 20+ Year Treasury Bond ETF',
      price: 99.4,
      changePct: 1.25,
      volumeRatio: 2.2,
      attentionScore: 78,
      why: 'Jobless claims revision reinforces 50bps Fed cut odds; 10-year yield breaks down through 3.75%',
      tags: ['Macro', 'Rates', 'Volume'],
      dataStatus: 'live',
      sparkline: [98.1, 98.4, 98.8, 99.0, 99.1, 99.3, 99.4],
      marketCap: '$58B',
      high52w: 101.5,
      low52w: 82.4,
    },
    {
      symbol: 'GLD',
      companyName: 'SPDR Gold Shares',
      price: 231.8,
      changePct: 0.95,
      volumeRatio: 1.4,
      attentionScore: 65,
      why: 'Central bank physical reserves diversification pace continues; all-time high retest in progress',
      tags: ['Commodities', 'Breakout'],
      dataStatus: 'live',
      sparkline: [229.5, 230.1, 230.8, 231.2, 231.4, 231.6, 231.8],
      marketCap: '$67B',
      high52w: 233.1,
      low52w: 172.4,
    },
    {
      symbol: 'UUP',
      companyName: 'Invesco DB US Dollar Index Bullish',
      price: 28.12,
      changePct: -0.68,
      volumeRatio: 1.3,
      attentionScore: 56,
      why: 'DXY slides under 101.0 handle following dovish FOMC minutes commentary',
      tags: ['FX', 'Macro'],
      dataStatus: 'live',
      sparkline: [28.31, 28.25, 28.2, 28.18, 28.15, 28.13, 28.12],
      marketCap: '$440M',
      high52w: 29.8,
      low52w: 27.5,
    },
    {
      symbol: 'HYG',
      companyName: 'iShares iBoxx $ High Yield Corporate Bond',
      price: 78.45,
      changePct: 0.15,
      volumeRatio: 0.65,
      attentionScore: 22,
      why: 'Credit spreads narrow to near cycle tightest 290bps; default risk subdued',
      tags: ['Credit'],
      dataStatus: 'delayed',
      sparkline: [78.3, 78.35, 78.4, 78.42, 78.43, 78.44, 78.45],
      marketCap: '$17B',
      high52w: 79.1,
      low52w: 72.3,
    },
  ],
  'empty-watchlist': [],
};

export const INITIAL_DIFFS_BY_WATCHLIST: Record<string, WatchlistDiffItem[]> = {
  'core-tech': [
    {
      symbol: 'NVDA',
      companyName: 'NVIDIA Corporation',
      price: 132.84,
      changePct: 4.82,
      why: 'Blackwell packaging bottlenecks resolved; supply deliveries accelerated to hyperscalers',
      flagged: true,
      attentionScore: 94,
      tags: ['Volume', 'Breakout'],
    },
    {
      symbol: 'PLTR',
      companyName: 'Palantir Technologies Inc.',
      price: 36.42,
      changePct: 7.15,
      why: 'Confirmed S&P 500 inclusion; massive passive institutional index fund rebalance demand',
      flagged: true,
      attentionScore: 91,
      tags: ['Earnings', 'Volume'],
    },
    {
      symbol: 'ASML',
      companyName: 'ASML Holding N.V.',
      price: 884.2,
      changePct: -3.41,
      why: 'Dutch government issues stricter lithography export restrictions without US coordination',
      flagged: true,
      attentionScore: 88,
      tags: ['Regulatory', 'Guidance'],
    },
    {
      symbol: 'ARM',
      companyName: 'Arm Holdings plc',
      price: 139.6,
      changePct: 3.25,
      why: 'Royalties expanding 2x on next-generation AI chip architectures',
      flagged: false,
      attentionScore: 72,
      tags: ['Guidance'],
    },
    {
      symbol: 'AMD',
      companyName: 'Advanced Micro Devices',
      price: 154.2,
      changePct: -1.92,
      why: 'Competitive pressure in traditional enterprise x86 compute',
      flagged: false,
      attentionScore: 64,
      tags: ['Competitive'],
    },
  ],
  'biopharma-edge': [
    {
      symbol: 'VRTX',
      companyName: 'Vertex Pharmaceuticals',
      price: 488.75,
      changePct: 5.42,
      why: 'FDA granted priority review for Suzetrigine acute pain treatment with January PDUFA target',
      flagged: true,
      attentionScore: 92,
      tags: ['FDA Approval', 'Volume'],
    },
    {
      symbol: 'CRSP',
      companyName: 'CRISPR Therapeutics',
      price: 52.3,
      changePct: -4.12,
      why: 'Hospital onboarding throughput for gene editing cell therapy lagging analyst models',
      flagged: true,
      attentionScore: 81,
      tags: ['Earnings', 'Volume'],
    },
    {
      symbol: 'LLY',
      companyName: 'Eli Lilly and Company',
      price: 942.1,
      changePct: 2.35,
      why: 'Expanded production vial lines lowering unit manufacturing cost significantly',
      flagged: false,
      attentionScore: 84,
      tags: ['Catalyst'],
    },
  ],
  'macro-etfs': [
    {
      symbol: 'TLT',
      companyName: 'iShares 20+ Year Treasury',
      price: 99.4,
      changePct: 1.25,
      why: 'Benchmark yields break multi-month support on soft economic indicators',
      flagged: true,
      attentionScore: 78,
      tags: ['Macro', 'Rates'],
    },
    {
      symbol: 'GLD',
      companyName: 'SPDR Gold Shares',
      price: 231.8,
      changePct: 0.95,
      why: 'Gold physical ETF inflows hit highest monthly surge since 2020',
      flagged: false,
      attentionScore: 65,
      tags: ['Breakout'],
    },
  ],
  'empty-watchlist': [],
};

export const SYMBOL_DICTIONARY = [
  { symbol: 'NVDA', name: 'NVIDIA Corporation', defaultWhy: 'GPU computing and AI platform acceleration', defaultTags: ['AI', 'Semis', 'Volume'] },
  { symbol: 'AAPL', name: 'Apple Inc.', defaultWhy: 'Hardware ecosystem and high-margin services cashflow', defaultTags: ['Consumer', 'Tech'] },
  { symbol: 'MSFT', name: 'Microsoft Corporation', defaultWhy: 'Cloud computing Azure and enterprise AI Copilot monetization', defaultTags: ['Cloud', 'Enterprise'] },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', defaultWhy: 'Search advertising rebound and Gemini infrastructure buildout', defaultTags: ['Search', 'AI'] },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', defaultWhy: 'AWS cloud re-acceleration and retail margin expansion', defaultTags: ['Cloud', 'E-commerce'] },
  { symbol: 'META', name: 'Meta Platforms Inc.', defaultWhy: 'Llama models integration and Meta AI ad engagement gains', defaultTags: ['Ads', 'Social'] },
  { symbol: 'TSLA', name: 'Tesla, Inc.', defaultWhy: 'FSD autonomous compute milestone and energy storage growth', defaultTags: ['EV', 'Autonomy'] },
  { symbol: 'AVGO', name: 'Broadcom Inc.', defaultWhy: 'Custom AI ASIC silicon partnerships with hyperscalers', defaultTags: ['Semis', 'AI'] },
  { symbol: 'SMCI', name: 'Super Micro Computer', defaultWhy: 'Liquid-cooled server rack shipments for enterprise clusters', defaultTags: ['Hardware', 'Volume'] },
  { symbol: 'COIN', name: 'Coinbase Global, Inc.', defaultWhy: 'Spot ETF custody fees and layer-2 Base transaction growth', defaultTags: ['Crypto', 'Fintech'] },
  { symbol: 'UBER', name: 'Uber Technologies, Inc.', defaultWhy: 'Autonomous fleet partner integrations and free cash flow generation', defaultTags: ['Mobility', 'Profitability'] },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings', defaultWhy: 'Falcon platform Falcon Flex contracts renewal strength', defaultTags: ['Cybersecurity', 'SaaS'] },
];

